# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    strategy:
      matrix:
        # Modify hw-out with the name of the .out file in the correct order
        # script is for hw1, data for 2, cluster for 3...
        hw-out: [script, data, cluster, grid, bins, xpln, stats, project]
        
    env:
      NUM: ${{ strategy.job-index }} 
      
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Get HW Name
      run: |
        if [ "${{matrix.hw-out}}" == "project" ]; 
        then echo "HW-NAME=Project" >> $GITHUB_ENV; 
        else echo "HW-NAME=HW$(($NUM+1))" >> $GITHUB_ENV; fi
        
        
    - name: Check if exists
      run: |
        echo "src/${{ env.HW-NAME }}"
        echo "HW-EXISTS=$(if [ -d "src/${{ env.HW-NAME }}" ]; then echo true; else echo false; fi)" >> $GITHUB_ENV
    
    - name: Display Variables
      run: | 
        echo Name: ${{ env.HW-NAME }}
        echo Exists: ${{ env.HW-EXISTS }}
        
    - name: Run ${{ env.HW-NAME }} Tests
      if: ${{ env.HW-EXISTS == 'true' }}
      run: |
        python test/test_hw.py "${{ env.HW-NAME }}" > out/${{matrix.hw-out}}.out
        cat out/${{matrix.hw-out}}.out
      
    - name: Save .out files
      if: always()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Save *.out files
        file_pattern: '*.out'
