# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEVOPS_DIR: devops

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    strategy:
      matrix:
        hw-out: [script, data, cluster, grid]
    env:
      NUM: ${{ strategy.job-index }}    
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Check-out repository
      uses: actions/checkout@v2
      with:
        repository: manoj-ayyappan/engr-csc591-021-spring2023
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}
        
    - name: Get HW Number
      run: echo "HW-NUM=$(($NUM+1))" >> $GITHUB_ENV
      
    - name: Run HW${{ env.HW-NUM }} Tests
      run: python test/test_hw.py "HW${{ env.HW-NUM }}" > out/${{matrix.hw-out}}.out; cat out/${{matrix.hw-out}}.out
      working-directory: ${{ env.DEVOPS_DIR }}
    
    - name: List dirs
      run: tree ${{ env.DEVOPS_DIR }}
      
    - name: Save .out files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Save *.out files
        file_pattern: '*.out'
        repository: ${{ env.DEVOPS_DIR }}
        
