# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEVOPS_DIR: devops

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Check-out repository
      uses: actions/checkout@v2
      with:
        repository: manoj-ayyappan/engr-csc591-021-spring2023
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Run HW1 Tests
      run: python ../test/test_hw1.py > script.out
      working-directory: ${{ env.DEVOPS_DIR }}/HW1/src
            
    - name: Run HW2 Tests
      run: python ../test/test_hw2.py > data.out
      working-directory: ${{ env.DEVOPS_DIR }}/HW2/src
    
    - name: out-files
      uses: actions/upload-artifact@v3
      with:
        path: ${{ env.DEVOPS_DIR }}/**/src/*.out
